# Generated by Django 3.1.4 on 2021-03-11 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
                ('number', models.IntegerField(default=0, verbose_name='出目')),
                ('types', models.IntegerField(default=1, verbose_name='ルーレットタイプ')),
                ('place', models.TextField(default=0, max_length=10, verbose_name='場所')),
                ('company', models.TextField(default=0, max_length=10, verbose_name='製作会社')),
            ],
        ),
    ]
